spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lemall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.zzzl.lemall.domain

