spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lemall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    #配置redis0
    database: 0
    host: 127.0.0.1
    port: 6379
#logging:
#  level: debug


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.zzzl.lemall.domain
